version: '2'

services:
   db:
     image: mysql:5.7
     networks:
      testing_net:
          ipv4_address: 172.28.1.2
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     container_name: wp_ryt
     depends_on:
       - db
     image: wordpress:latest
     networks:
       testing_net:
          ipv4_address: 172.28.1.1
     ports:
       - 8080:80
     volumes:
       - ./:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: {}
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
# RUN sudo chmod 644 -R ./


