version: '2'

services:
   db:
     image: mysql:5.7
     ports:
      - 3306:3306
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     container_name: wp_bam
     depends_on:
       - db
     image: wordpress:4.9.8
     ports:
       - 8080:80
     volumes:
       - ./:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: {}

# RUN sudo chmod 644 -R ./


